<a href="https://colab.research.google.com/github/muskan628/Python-Projects/blob/main/Sales_Data_Analysis_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

#Sales dataset
sales_data=np.random.randint(100,10001,size=5000)

#Products dataset
product_categories=np.random.randint(1,11,size=5000)

print(f"First Five Sales Figures: {sales_data[0:10]}")
print(f"First Five Product Categories: {product_categories[0:10]}")

#Basic Operations
Total_Sales=np.sum(sales_data)
average_sales=np.mean(sales_data)
max_sales=np.max(sales_data)
min_sales=np.min(sales_data)
print()

print(f"Total Sales: {Total_Sales}")
print(f"Average Sales: {average_sales:.2f}")
print(f"Maximum Sales: {max_sales}")
print(f"Minimum Sales: {min_sales}")
print()

#Combined Dataset
combined_data=np.stack((sales_data,product_categories), axis=1)
print(f"First Five rows of Combined dataset: \n{combined_data[0:5]}")
print()

above_avg=combined_data[sales_data>average_sales]
below_avg=combined_data[sales_data<average_sales]
print(f"Sales Above Average: {len(above_avg)}")
print(f"Sales below avg {len(below_avg)}")
print()

above_8000=combined_data[sales_data>8000]
print(f"Sales above 8000: \n{above_8000[:5]}")
print()

sorting=combined_data[combined_data[:, 0].argsort()]
print(f"Sorted Data: \n{sorting}")
print()

filtering=sorting[sorting[:, 0] > 5000]
print(f"Filtered Data: {filtering[:5]}")



First Five Sales Figures: [1409  329 6305 8957  844 1158  483 3327 2307  834]
First Five Product Categories: [6 7 2 5 3 1 4 5 2 8]

Total Sales: 25253663
Average Sales: 5050.73
Maximum Sales: 10000
Minimum Sales: 103

First Five rows of Combined dataset: 
[[1409    6]
 [ 329    7]
 [6305    2]
 [8957    5]
 [ 844    3]]

Sales Above Average: 2463
Sales below avg 2537

Sales above 8000: 
[[8957    5]
 [9797    9]
 [9771    1]
 [9550    2]
 [9904    2]]

Sorted Data: 
[[  103    10]
 [  105     4]
 [  107     1]
 ...
 [ 9994     2]
 [10000    10]
 [10000    10]]

Filtered Data: [[5001    9]
 [5002    7]
 [5005    8]
 [5007   10]
 [5009    9]]
